import type { Movie } from "./Types";

export const MovieData: Movie[] = [
  {
    title: "Love by Drowning",
    rating: "R",
    genre: "Drama",
    year: 2020,
    runtime: 121,
    director: "Justin Kreinbrink",
  },
  {
    title: "The Shawshank Redemption",
    rating: "R",
    genre: "Drama",
    year: 1994,
    runtime: 142,
    director: "Frank Darabont",
  },
  {
    title: "The Dark Knight",
    rating: "PG-13",
    genre: "Action",
    year: 2008,
    runtime: 152,
    director: "Christopher Nolan",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    rating: "PG-13",
    genre: "Action",
    year: 2003,
    runtime: 201,
    director: "Peter Jackson",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    rating: "PG-13",
    genre: "Action",
    year: 2001,
    runtime: 178,
    director: "Peter Jackson",
  },
  {
    title: "Forrest Gump",
    rating: "PG-13",
    genre: "Drama",
    year: 1994,
    runtime: 142,
    director: "Robert Zemeckis",
  },
  {
    title: "Fight Club",
    rating: "R",
    genre: "Drama",
    year: 1999,
    runtime: 139,
    director: "David Fincher",
  },
  {
    title: "Inception",
    rating: "PG-13",
    genre: "Action",
    year: 2010,
    runtime: 148,
    director: "Christopher Nolan",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    rating: "PG",
    genre: "Action",
    year: 1980,
    runtime: 124,
    director: "Irvin Kershner",
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    rating: "PG-13",
    genre: "Action",
    year: 2002,
    runtime: 179,
    director: "Peter Jackson",
  },
  {
    title: "The Matrix",
    rating: "R",
    genre: "Action",
    year: 1999,
    runtime: 136,
    director: "Lana Wachowski",
  },
  {
    title: "Saving Private Ryan",
    rating: "R",
    genre: "Drama",
    year: 1998,
    runtime: 169,
    director: "Steven Spielberg",
  },
  {
    title: "Parasite",
    rating: "R",
    genre: "Comedy",
    year: 2019,
    runtime: 132,
    director: "Bong Joon Ho",
  },
  {
    title: "Life Is Beautiful",
    rating: "PG-13",
    genre: "Comedy",
    year: 1997,
    runtime: 116,
    director: "Roberto Benigni",
  },
  {
    title: "The Prestige",
    rating: "PG-13",
    genre: "Drama",
    year: 2006,
    runtime: 130,
    director: "Christopher Nolan",
  },
  {
    title: "Gladiator",
    rating: "R",
    genre: "Action",
    year: 2000,
    runtime: 155,
    director: "Ridley Scott",
  },
  {
    title: "Terminator 2: Judgment Day",
    rating: "R",
    genre: "Action",
    year: 1991,
    runtime: 137,
    director: "James Cameron",
  },
  {
    title: "Cinema Paradiso",
    rating: "PG",
    genre: "Drama",
    year: 1988,
    runtime: 155,
    director: "Giuseppe Tornatore",
  },
  {
    title: "American History X",
    rating: "R",
    genre: "Drama",
    year: 1998,
    runtime: 119,
    director: "Tony Kaye",
  },
  {
    title: "Léon: The Professional",
    rating: "R",
    genre: "Action",
    year: 1994,
    runtime: 110,
    director: "Luc Besson",
  },
  {
    title: "The Best of Youth",
    rating: "R",
    genre: "Drama",
    year: 2003,
    runtime: 366,
    director: "Marco Tullio Giordana",
  },
  {
    title: "Whiplash",
    rating: "R",
    genre: "Drama",
    year: 2014,
    runtime: 106,
    director: "Damien Chazelle",
  },
  {
    title: "The Dark Knight Rises",
    rating: "PG-13",
    genre: "Action",
    year: 2012,
    runtime: 164,
    director: "Christopher Nolan",
  },
  {
    title: "Django Unchained",
    rating: "R",
    genre: "Drama",
    year: 2012,
    runtime: 165,
    director: "Quentin Tarantino",
  },
  {
    title: "Indiana Jones and the Raiders of the Lost Ark",
    rating: "PG",
    genre: "Action",
    year: 1981,
    runtime: 115,
    director: "Steven Spielberg",
  },
  {
    title: "Capharnaüm",
    rating: "R",
    genre: "Drama",
    year: 2018,
    runtime: 126,
    director: "Nadine Labaki",
  },
  {
    title: "The Shining",
    rating: "R",
    genre: "Drama",
    year: 1980,
    runtime: 146,
    director: "Stanley Kubrick",
  },
  {
    title: "Oldboy",
    rating: "R",
    genre: "Action",
    year: 2003,
    runtime: 120,
    director: "Park Chan-Wook",
  },
  {
    title: "Avengers: Infinity War",
    rating: "PG-13",
    genre: "Action",
    year: 2018,
    runtime: 149,
    director: "Anthony Russo",
  },
  {
    title: "The Lives of Others",
    rating: "R",
    genre: "Drama",
    year: 2006,
    runtime: 137,
    director: "Florian Henckel von Donnersmarck",
  },
  {
    title: "Like Stars on Earth",
    rating: "PG",
    genre: "Drama",
    year: 2007,
    runtime: 165,
    director: "Aamir Khan",
  },
  {
    title: "Avengers: Endgame",
    rating: "PG-13",
    genre: "Action",
    year: 2019,
    runtime: 181,
    director: "Anthony Russo",
  },
  {
    title: "3 Idiots",
    rating: "PG-13",
    genre: "Comedy",
    year: 2009,
    runtime: 170,
    director: "Rajkumar Hirani",
  },
  {
    title: "1917",
    rating: "R",
    genre: "Drama",
    year: 2019,
    runtime: 119,
    director: "Sam Mendes",
  },
  {
    title: "American Beauty",
    rating: "R",
    genre: "Drama",
    year: 1999,
    runtime: 122,
    director: "Sam Mendes",
  },
  {
    title: "Repentance",
    rating: "PG",
    genre: "Drama",
    year: 1984,
    runtime: 153,
    director: "Tengiz Abuladze",
  },
  {
    title: "The Hunt",
    rating: "R",
    genre: "Drama",
    year: 2012,
    runtime: 115,
    director: "Thomas Vinterberg",
  },
  {
    title: "Children of Heaven",
    rating: "PG",
    genre: "Drama",
    year: 1997,
    runtime: 89,
    director: "Majid Majidi",
  },
  {
    title: "Snatch",
    rating: "R",
    genre: "Comedy",
    year: 2000,
    runtime: 102,
    director: "Guy Ritchie",
  },
  {
    title: "Amélie",
    rating: "R",
    genre: "Comedy",
    year: 2001,
    runtime: 122,
    director: "Jean-Pierre Jeunet",
  },
  {
    title: "A Separation",
    rating: "PG-13",
    genre: "Drama",
    year: 2011,
    runtime: 123,
    director: "Asghar Farhadi",
  },
  {
    title: "Full Metal Jacket",
    rating: "R",
    genre: "Drama",
    year: 1987,
    runtime: 116,
    director: "Stanley Kubrick",
  },
  {
    title: "Incendies",
    rating: "R",
    genre: "Drama",
    year: 2010,
    runtime: 131,
    director: "Denis Villeneuve",
  },
  {
    title: "Star Wars: Episode VI - Return of the Jedi",
    rating: "PG",
    genre: "Action",
    year: 1983,
    runtime: 131,
    director: "Richard Marquand",
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    rating: "R",
    genre: "Drama",
    year: 2004,
    runtime: 108,
    director: "Michel Gondry",
  },
  {
    title: "Good Will Hunting",
    rating: "R",
    genre: "Drama",
    year: 1997,
    runtime: 126,
    director: "Gus Van Sant",
  },
  {
    title: "Aliens",
    rating: "R",
    genre: "Action",
    year: 1986,
    runtime: 137,
    director: "James Cameron",
  },
  {
    title: "There Will Be Blood",
    rating: "R",
    genre: "Drama",
    year: 2007,
    runtime: 158,
    director: "Paul Thomas Anderson",
  },
  {
    title: "Indiana Jones and the Last Crusade",
    rating: "PG-13",
    genre: "Action",
    year: 1989,
    runtime: 127,
    director: "Steven Spielberg",
  },
  {
    title: "Time of the Gypsies",
    rating: "R",
    genre: "Comedy",
    year: 1988,
    runtime: 142,
    director: "Emir Kusturica",
  },
  {
    title: "The Color of Paradise",
    rating: "PG",
    genre: "Drama",
    year: 1999,
    runtime: 90,
    director: "Majid Majidi",
  },
  {
    title: "Lock, Stock and Two Smoking Barrels",
    rating: "R",
    genre: "Action",
    year: 1998,
    runtime: 107,
    director: "Guy Ritchie",
  },
  {
    title: "The Secret in Their Eyes",
    rating: "R",
    genre: "Drama",
    year: 2009,
    runtime: 129,
    director: "Juan José Campanella",
  },
  {
    title: "Unforgiven",
    rating: "R",
    genre: "Drama",
    year: 1992,
    runtime: 130,
    director: "Clint Eastwood",
  },
  {
    title: "Batman Begins",
    rating: "PG-13",
    genre: "Action",
    year: 2005,
    runtime: 140,
    director: "Christopher Nolan",
  },
  {
    title: "Die Hard",
    rating: "R",
    genre: "Action",
    year: 1988,
    runtime: 132,
    director: "John McTiernan",
  },
  {
    title: "Pan's Labyrinth",
    rating: "R",
    genre: "Drama",
    year: 2006,
    runtime: 118,
    director: "Guillermo del Toro",
  },
  {
    title: "Ran",
    rating: "R",
    genre: "Action",
    year: 1985,
    runtime: 162,
    director: "Akira Kurosawa",
  },
  {
    title: "The Sixth Sense",
    rating: "PG-13",
    genre: "Drama",
    year: 1999,
    runtime: 107,
    director: "M. Night Shyamalan",
  },
  {
    title: "Wild Tales",
    rating: "R",
    genre: "Comedy",
    year: 2014,
    runtime: 122,
    director: "Damián Szifron",
  },
  {
    title: "The Truman Show",
    rating: "PG",
    genre: "Comedy",
    year: 1998,
    runtime: 103,
    director: "Peter Weir",
  },
  {
    title: "V for Vendetta",
    rating: "R",
    genre: "Action",
    year: 2005,
    runtime: 132,
    director: "James McTeigue",
  },
  {
    title: "Gran Torino",
    rating: "R",
    genre: "Drama",
    year: 2008,
    runtime: 116,
    director: "Clint Eastwood",
  },
  {
    title: "Moscow Does Not Believe in Tears",
    rating: "PG",
    genre: "Comedy",
    year: 1980,
    runtime: 150,
    director: "Vladimir Menshov",
  },
  {
    title: "The Celebration",
    rating: "R",
    genre: "Drama",
    year: 1998,
    runtime: 105,
    director: "Thomas Vinterberg",
  },
  {
    title: "Ford v Ferrari",
    rating: "PG-13",
    genre: "Action",
    year: 2019,
    runtime: 152,
    director: "James Mangold",
  },
  {
    title: "Three Colors: Red",
    rating: "R",
    genre: "Drama",
    year: 1994,
    runtime: 99,
    director: "Krzysztof Kieslowski",
  },
  {
    title: "Mad Max: Fury Road",
    rating: "R",
    genre: "Action",
    year: 2015,
    runtime: 120,
    director: "George Miller",
  },
  {
    title: "Fanny and Alexander",
    rating: "R",
    genre: "Drama",
    year: 1982,
    runtime: 188,
    director: "Ingmar Bergman",
  },
  {
    title: "Departures",
    rating: "PG-13",
    genre: "Drama",
    year: 2008,
    runtime: 130,
    director: "Yôjirô Takita",
  },
  {
    title: "Farewell My Concubine",
    rating: "R",
    genre: "Drama",
    year: 1993,
    runtime: 171,
    director: "Kaige Chen",
  },
  {
    title: "The Big Lebowski",
    rating: "R",
    genre: "Comedy",
    year: 1998,
    runtime: 117,
    director: "Joel Coen",
  },
  {
    title: "Jurassic Park",
    rating: "PG-13",
    genre: "Action",
    year: 1993,
    runtime: 127,
    director: "Steven Spielberg",
  },
  {
    title: "Mommy",
    rating: "R",
    genre: "Drama",
    year: 2014,
    runtime: 139,
    director: "Xavier Dolan",
  },
  {
    title: "Dead Poets Society",
    rating: "PG",
    genre: "Comedy",
    year: 1989,
    runtime: 128,
    director: "Peter Weir",
  },
  {
    title: "Platoon",
    rating: "R",
    genre: "Drama",
    year: 1986,
    runtime: 120,
    director: "Oliver Stone",
  },
  {
    title: "Blade Runner",
    rating: "R",
    genre: "Action",
    year: 1982,
    runtime: 117,
    director: "Ridley Scott",
  },
  {
    title: "Lagaan: Once Upon a Time in India",
    rating: "PG",
    genre: "Drama",
    year: 2001,
    runtime: 224,
    director: "Ashutosh Gowariker",
  },
  {
    title: "The Legend of 1900",
    rating: "R",
    genre: "Drama",
    year: 1998,
    runtime: 169,
    director: "Giuseppe Tornatore",
  },
  {
    title: "Portrait of a Lady on Fire",
    rating: "R",
    genre: "Drama",
    year: 2019,
    runtime: 122,
    director: "Céline Sciamma",
  },
  {
    title: "Warrior",
    rating: "PG-13",
    genre: "Action",
    year: 2011,
    runtime: 140,
    director: "Gavin O'Connor",
  },
  {
    title: "Gone Girl",
    rating: "R",
    genre: "Drama",
    year: 2014,
    runtime: 149,
    director: "David Fincher",
  },
  {
    title: "Amores Perros",
    rating: "R",
    genre: "Drama",
    year: 2000,
    runtime: 154,
    director: "Alejandro G. Iñárritu",
  },
  {
    title: "Paris, Texas",
    rating: "R",
    genre: "Drama",
    year: 1984,
    runtime: 145,
    director: "Wim Wenders",
  },
  {
    title: "Nobody Knows",
    rating: "PG-13",
    genre: "Drama",
    year: 2004,
    runtime: 141,
    director: "Hirokazu Koreeda",
  },
  {
    title: "Rush",
    rating: "R",
    genre: "Action",
    year: 2013,
    runtime: 123,
    director: "Ron Howard",
  },
  {
    title: "Kill Bill: Vol. 1",
    rating: "R",
    genre: "Action",
    year: 2003,
    runtime: 111,
    director: "Quentin Tarantino",
  },
  {
    title: "Crna macka, beli macor",
    rating: "R",
    genre: "Comedy",
    year: 1998,
    runtime: 127,
    director: "Emir Kusturica",
  },
  {
    title: "Before Sunset",
    rating: "R",
    genre: "Drama",
    year: 2004,
    runtime: 80,
    director: "Richard Linklater",
  },
  {
    title: "Before Sunrise",
    rating: "R",
    genre: "Drama",
    year: 1995,
    runtime: 101,
    director: "Richard Linklater",
  },
  {
    title: "In the Mood for Love",
    rating: "PG",
    genre: "Drama",
    year: 2000,
    runtime: 98,
    director: "Kar-Wai Wong",
  },
  {
    title: "Trainspotting",
    rating: "R",
    genre: "Drama",
    year: 1996,
    runtime: 93,
    director: "Danny Boyle",
  },
  {
    title: "Million Dollar Baby",
    rating: "PG-13",
    genre: "Drama",
    year: 2004,
    runtime: 132,
    director: "Clint Eastwood",
  },
  {
    title: "Raise the Red Lantern",
    rating: "PG",
    genre: "Drama",
    year: 1991,
    runtime: 125,
    director: "Yimou Zhang",
  },
  {
    title: "Chungking Express",
    rating: "PG-13",
    genre: "Comedy",
    year: 1994,
    runtime: 102,
    director: "Kar-Wai Wong",
  },
  {
    title: "Room",
    rating: "R",
    genre: "Drama",
    year: 2015,
    runtime: 118,
    director: "Lenny Abrahamson",
  },
  {
    title: "Three Billboards Outside Ebbing, Missouri",
    rating: "R",
    genre: "Comedy",
    year: 2017,
    runtime: 115,
    director: "Martin McDonagh",
  },
  {
    title: "Logan",
    rating: "R",
    genre: "Action",
    year: 2017,
    runtime: 137,
    director: "James Mangold",
  },
  {
    title: "The Sacrifice",
    rating: "PG",
    genre: "Drama",
    year: 1986,
    runtime: 149,
    director: "Andrei Tarkovsky",
  },
  {
    title: "Spring, Summer, Fall, Winter... and Spring",
    rating: "R",
    genre: "Drama",
    year: 2003,
    runtime: 103,
    director: "Kim Ki-duk",
  },
];
